name: Deploy to Azure VM

on:
  push:
    branches: [master] 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3  
        with:
          host: ${{ secrets.AZURE_HOST }}  # IP-адреса вашої VM
          username: ${{ secrets.AZURE_USERNAME }}  # Ім'я користувача для SSH підключення
          key: ${{ secrets.SSH_PRIVATE_KEY_AZURE }}  # Приватний SSH ключ для доступу до VM
          port: 22  # Стандартний порт для SSH
          script: |
            echo "Starting deployment..."
            cd ~/database-flask  # Перехід до директорії вашого проєкту

            echo "Pulling latest changes..."
            git fetch origin  # Отримуємо останні зміни з віддаленого репозиторію
            git reset --hard origin/lab5  # Оновлюємо локальну гілку до останнього коміту в lab5

            echo "Setting up environment variables..."
            echo "DB_HOST=${{ secrets.DB_HOST_AZURE }}" > .env  # Додавання DB_HOST, якщо потрібно
            echo "DB_USERNAME=${{ secrets.DB_USERNAME_AZURE }}" >> .env  # Додаємо ім'я користувача БД
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_AZURE }}" >> .env  # Додаємо пароль БД
            echo "FLASK_APP=app.py" >> .env  # Приклад змінної середовища для Flask
            echo "FLASK_ENV=production" >> .env  # Налаштування середовища для Flask

            echo "Restarting service..."
            sudo systemctl restart hospital-app  # Перезапускаємо ваш додаток (наприклад, Flask app)

            echo "Checking service status..."
            sudo systemctl status hospital-app --no-pager  # Перевіряємо статус сервісу

            echo "Deployment completed!"  # Завершуємо деплоймент
