name: Deploy Flask App to Azure App Service

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: './db-flask-main'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: 'Install dependencies'
      run: |
        pip install --upgrade pip
        pip install -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/requirements.txt

    - name: 'Check if startup.sh exists'
      run: |
        if [ ! -f "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh" ]; then
          echo "ERROR: startup.sh not found"
          exit 1
        fi

    - name: 'Make startup.sh executable'
      run: chmod +x ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh
    
    - name: 'Run tests'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        python -m pytest tests/ || echo "No tests found, continuing..."
        
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        startup-command: 'bash ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh'
